description = "Ubuntu 26.04 Resolute Raccoon base image with no buildpacks included. To use, specify buildpacks at build time."

[build]
  image = "docker.io/paketobuildpacks/ubuntu-resolute-build:0.0.13"

[lifecycle]
  version = "0.21.17"

[run]

  [[run.images]]
    image = "docker.io/paketobuildpacks/ubuntu-resolute-run:latest"

[stack]
  id = "io.buildpacks.stacks.resolute"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
