description = "Ubuntu 26.04 Resolute Raccoon base image with buildpacks for Java, Node.js, .NET, Nginx and Procfile"

[build]
  image = "docker.io/paketobuildpacks/ubuntu-resolute-build:0.0.7"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java-native-image:14.8.0"
  version = "14.8.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/java:22.2.0"
  version = "22.2.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/nodejs:10.7.0"
  version = "10.7.0"

[[buildpacks]]
  uri = "docker://docker.io/paketobuildpacks/procfile:5.13.6"
  version = "5.13.6"

[lifecycle]
  version = "0.21.14"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java-native-image"
    version = "14.8.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/java"
    version = "22.2.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/nodejs"
    version = "10.7.0"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    version = "5.13.6"

[run]

  [[run.images]]
    image = "docker.io/paketobuildpacks/ubuntu-resolute-run:latest"

[stack]
  id = "io.buildpacks.stacks.resolute"

[[targets]]
  arch = "amd64"
  os = "linux"

[[targets]]
  arch = "arm64"
  os = "linux"
